---
- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://downloads.plex.tv/plex-keys/PlexSign.key
    state: present
  
- name: setup the apt repo
  apt_repository:
    repo: 'deb https://downloads.plex.tv/repo/deb public main'
    state: present
    filename: plexmediaserver

- name: install plex media server
  apt:
    name: plexmediaserver
    update_cache: True
